#pragma once
#include <cstdint>
#include <string_view>

namespace mc189 {

// Block IDs matching Minecraft 1.8.9
enum class BlockID : uint16_t {
    AIR = 0,
    STONE = 1,
    GRASS = 2,
    DIRT = 3,
    COBBLESTONE = 4,
    PLANKS = 5,
    SAPLING = 6,
    BEDROCK = 7,
    WATER = 8,
    WATER_STILL = 9,
    LAVA = 10,
    LAVA_STILL = 11,
    SAND = 12,
    GRAVEL = 13,
    GOLD_ORE = 14,
    IRON_ORE = 15,
    COAL_ORE = 16,
    LOG = 17,
    LEAVES = 18,
    SPONGE = 19,
    GLASS = 20,
    LAPIS_ORE = 21,
    LAPIS_BLOCK = 22,
    DISPENSER = 23,
    SANDSTONE = 24,
    NOTEBLOCK = 25,
    BED = 26,
    GOLDEN_RAIL = 27,
    DETECTOR_RAIL = 28,
    STICKY_PISTON = 29,
    COBWEB = 30,
    TALLGRASS = 31,
    DEADBUSH = 32,
    PISTON = 33,
    PISTON_HEAD = 34,
    WOOL = 35,
    PISTON_EXTENSION = 36,
    YELLOW_FLOWER = 37,
    RED_FLOWER = 38,
    BROWN_MUSHROOM = 39,
    RED_MUSHROOM = 40,
    GOLD_BLOCK = 41,
    IRON_BLOCK = 42,
    DOUBLE_STONE_SLAB = 43,
    STONE_SLAB = 44,
    BRICK_BLOCK = 45,
    TNT = 46,
    BOOKSHELF = 47,
    MOSSY_COBBLESTONE = 48,
    OBSIDIAN = 49,
    TORCH = 50,
    FIRE = 51,
    MOB_SPAWNER = 52,
    OAK_STAIRS = 53,
    CHEST = 54,
    REDSTONE_WIRE = 55,
    DIAMOND_ORE = 56,
    DIAMOND_BLOCK = 57,
    CRAFTING_TABLE = 58,
    WHEAT = 59,
    FARMLAND = 60,
    FURNACE = 61,
    FURNACE_LIT = 62,
    SIGN = 63,
    WOODEN_DOOR = 64,
    LADDER = 65,
    RAIL = 66,
    COBBLESTONE_STAIRS = 67,
    WALL_SIGN = 68,
    LEVER = 69,
    STONE_PRESSURE_PLATE = 70,
    IRON_DOOR = 71,
    WOODEN_PRESSURE_PLATE = 72,
    REDSTONE_ORE = 73,
    REDSTONE_ORE_LIT = 74,
    REDSTONE_TORCH_OFF = 75,
    REDSTONE_TORCH = 76,
    BUTTON = 77,
    SNOW_LAYER = 78,
    ICE = 79,
    SNOW = 80,
    CACTUS = 81,
    CLAY = 82,
    REEDS = 83,
    JUKEBOX = 84,
    FENCE = 85,
    PUMPKIN = 86,
    NETHERRACK = 87,
    SOUL_SAND = 88,
    GLOWSTONE = 89,
    PORTAL = 90,
    JACK_O_LANTERN = 91,
    CAKE = 92,
    REPEATER_OFF = 93,
    REPEATER_ON = 94,
    STAINED_GLASS = 95,
    TRAPDOOR = 96,
    MONSTER_EGG = 97,
    STONEBRICK = 98,
    BROWN_MUSHROOM_BLOCK = 99,
    RED_MUSHROOM_BLOCK = 100,
    IRON_BARS = 101,
    GLASS_PANE = 102,
    MELON_BLOCK = 103,
    PUMPKIN_STEM = 104,
    MELON_STEM = 105,
    VINE = 106,
    FENCE_GATE = 107,
    BRICK_STAIRS = 108,
    STONE_BRICK_STAIRS = 109,
    MYCELIUM = 110,
    WATERLILY = 111,
    NETHER_BRICK = 112,
    NETHER_BRICK_FENCE = 113,
    NETHER_BRICK_STAIRS = 114,
    NETHER_WART = 115,
    ENCHANTING_TABLE = 116,
    BREWING_STAND = 117,
    CAULDRON = 118,
    END_PORTAL = 119,
    END_PORTAL_FRAME = 120,
    END_STONE = 121,
    DRAGON_EGG = 122,
    REDSTONE_LAMP = 123,
    REDSTONE_LAMP_LIT = 124,
    DOUBLE_WOODEN_SLAB = 125,
    WOODEN_SLAB = 126,
    COCOA = 127,
    SANDSTONE_STAIRS = 128,
    EMERALD_ORE = 129,
    ENDER_CHEST = 130,
    TRIPWIRE_HOOK = 131,
    TRIPWIRE = 132,
    EMERALD_BLOCK = 133,
    SPRUCE_STAIRS = 134,
    BIRCH_STAIRS = 135,
    JUNGLE_STAIRS = 136,
    COMMAND_BLOCK = 137,
    BEACON = 138,
    COBBLESTONE_WALL = 139,
    FLOWER_POT = 140,
    CARROTS = 141,
    POTATOES = 142,
    WOODEN_BUTTON = 143,
    SKULL = 144,
    ANVIL = 145,
    TRAPPED_CHEST = 146,
    LIGHT_WEIGHTED_PRESSURE_PLATE = 147,
    HEAVY_WEIGHTED_PRESSURE_PLATE = 148,
    COMPARATOR_OFF = 149,
    COMPARATOR_ON = 150,
    DAYLIGHT_DETECTOR = 151,
    REDSTONE_BLOCK = 152,
    QUARTZ_ORE = 153,
    HOPPER = 154,
    QUARTZ_BLOCK = 155,
    QUARTZ_STAIRS = 156,
    ACTIVATOR_RAIL = 157,
    DROPPER = 158,
    STAINED_HARDENED_CLAY = 159,
    STAINED_GLASS_PANE = 160,
    LEAVES2 = 161,
    LOG2 = 162,
    ACACIA_STAIRS = 163,
    DARK_OAK_STAIRS = 164,
    SLIME_BLOCK = 165,
    BARRIER = 166,
    IRON_TRAPDOOR = 167,
    PRISMARINE = 168,
    SEA_LANTERN = 169,
    HAY_BLOCK = 170,
    CARPET = 171,
    HARDENED_CLAY = 172,
    COAL_BLOCK = 173,
    PACKED_ICE = 174,
    DOUBLE_PLANT = 175,
    STANDING_BANNER = 176,
    WALL_BANNER = 177,
    DAYLIGHT_DETECTOR_INVERTED = 178,
    RED_SANDSTONE = 179,
    RED_SANDSTONE_STAIRS = 180,
    DOUBLE_STONE_SLAB2 = 181,
    STONE_SLAB2 = 182,
    SPRUCE_FENCE_GATE = 183,
    BIRCH_FENCE_GATE = 184,
    JUNGLE_FENCE_GATE = 185,
    DARK_OAK_FENCE_GATE = 186,
    ACACIA_FENCE_GATE = 187,
    SPRUCE_FENCE = 188,
    BIRCH_FENCE = 189,
    JUNGLE_FENCE = 190,
    DARK_OAK_FENCE = 191,
    ACACIA_FENCE = 192,
    SPRUCE_DOOR = 193,
    BIRCH_DOOR = 194,
    JUNGLE_DOOR = 195,
    ACACIA_DOOR = 196,
    DARK_OAK_DOOR = 197,

    MAX_BLOCK_ID = 256
};

struct BlockProperties {
    BlockID id;
    std::string_view name;
    float hardness;         // -1 = unbreakable
    float blast_resistance;
    bool solid;
    bool transparent;
    bool flammable;
    uint8_t light_emission; // 0-15
    uint8_t light_filter;   // How much light it blocks (0-15)
    bool replaceable;       // Can place block over it (air, water, tallgrass)
    bool gravity;           // Falls like sand/gravel
};

// clang-format off
constexpr BlockProperties BLOCK_PROPERTIES[] = {
    // ID                          name                    hard   blast   sol  trans  flam  emit filt repl grav
    {BlockID::AIR,                 "air",                  0,     0,      false, true,  false, 0,  0,  true,  false},
    {BlockID::STONE,               "stone",                1.5f,  6.0f,   true,  false, false, 0,  15, false, false},
    {BlockID::GRASS,               "grass",                0.6f,  0.6f,   true,  false, false, 0,  15, false, false},
    {BlockID::DIRT,                "dirt",                  0.5f,  0.5f,   true,  false, false, 0,  15, false, false},
    {BlockID::COBBLESTONE,         "cobblestone",           2.0f,  6.0f,   true,  false, false, 0,  15, false, false},
    {BlockID::PLANKS,              "planks",                2.0f,  3.0f,   true,  false, true,  0,  15, false, false},
    {BlockID::SAPLING,             "sapling",               0,     0,      false, true,  false, 0,  0,  true,  false},
    {BlockID::BEDROCK,             "bedrock",              -1,    18000000, true, false, false, 0,  15, false, false},
    {BlockID::WATER,               "water",                100,   500,    false, true,  false, 0,  2,  true,  false},
    {BlockID::WATER_STILL,         "water_still",          100,   500,    false, true,  false, 0,  2,  true,  false},
    {BlockID::LAVA,                "lava",                 100,   500,    false, true,  false, 15, 0,  true,  false},
    {BlockID::LAVA_STILL,          "lava_still",           100,   500,    false, true,  false, 15, 0,  true,  false},
    {BlockID::SAND,                "sand",                  0.5f,  0.5f,   true,  false, false, 0,  15, false, true},
    {BlockID::GRAVEL,              "gravel",                0.6f,  0.6f,   true,  false, false, 0,  15, false, true},
    {BlockID::GOLD_ORE,            "gold_ore",              3.0f,  3.0f,   true,  false, false, 0,  15, false, false},
    {BlockID::IRON_ORE,            "iron_ore",              3.0f,  3.0f,   true,  false, false, 0,  15, false, false},
    {BlockID::COAL_ORE,            "coal_ore",              3.0f,  3.0f,   true,  false, false, 0,  15, false, false},
    {BlockID::LOG,                 "log",                   2.0f,  2.0f,   true,  false, true,  0,  15, false, false},
    {BlockID::LEAVES,              "leaves",                0.2f,  0.2f,   true,  true,  true,  0,  1,  false, false},
    {BlockID::SPONGE,              "sponge",                0.6f,  0.6f,   true,  false, false, 0,  15, false, false},
    {BlockID::GLASS,               "glass",                 0.3f,  0.3f,   true,  true,  false, 0,  0,  false, false},
    {BlockID::LAPIS_ORE,           "lapis_ore",             3.0f,  3.0f,   true,  false, false, 0,  15, false, false},
    {BlockID::LAPIS_BLOCK,         "lapis_block",           3.0f,  3.0f,   true,  false, false, 0,  15, false, false},
    {BlockID::DISPENSER,           "dispenser",             3.5f,  3.5f,   true,  false, false, 0,  15, false, false},
    {BlockID::SANDSTONE,           "sandstone",             0.8f,  0.8f,   true,  false, false, 0,  15, false, false},
    {BlockID::NOTEBLOCK,           "noteblock",             0.8f,  0.8f,   true,  false, true,  0,  15, false, false},
    {BlockID::BED,                 "bed",                   0.2f,  0.2f,   true,  false, true,  0,  0,  false, false},
    {BlockID::GOLDEN_RAIL,         "golden_rail",           0.7f,  0.7f,   false, true,  false, 0,  0,  false, false},
    {BlockID::DETECTOR_RAIL,       "detector_rail",         0.7f,  0.7f,   false, true,  false, 0,  0,  false, false},
    {BlockID::STICKY_PISTON,       "sticky_piston",         0.5f,  0.5f,   true,  true,  false, 0,  0,  false, false},
    {BlockID::COBWEB,              "cobweb",                4.0f,  4.0f,   false, true,  false, 0,  0,  false, false},
    {BlockID::TALLGRASS,           "tallgrass",             0,     0,      false, true,  true,  0,  0,  true,  false},
    {BlockID::DEADBUSH,            "deadbush",              0,     0,      false, true,  true,  0,  0,  true,  false},
    {BlockID::PISTON,              "piston",                0.5f,  0.5f,   true,  true,  false, 0,  0,  false, false},
    {BlockID::PISTON_HEAD,         "piston_head",           0.5f,  0.5f,   true,  true,  false, 0,  0,  false, false},
    {BlockID::WOOL,                "wool",                  0.8f,  0.8f,   true,  false, true,  0,  15, false, false},
    {BlockID::YELLOW_FLOWER,       "yellow_flower",         0,     0,      false, true,  false, 0,  0,  true,  false},
    {BlockID::RED_FLOWER,          "red_flower",            0,     0,      false, true,  false, 0,  0,  true,  false},
    {BlockID::BROWN_MUSHROOM,      "brown_mushroom",        0,     0,      false, true,  false, 1,  0,  true,  false},
    {BlockID::RED_MUSHROOM,        "red_mushroom",          0,     0,      false, true,  false, 0,  0,  true,  false},
    {BlockID::GOLD_BLOCK,          "gold_block",            3.0f,  6.0f,   true,  false, false, 0,  15, false, false},
    {BlockID::IRON_BLOCK,          "iron_block",            5.0f,  6.0f,   true,  false, false, 0,  15, false, false},
    {BlockID::DOUBLE_STONE_SLAB,   "double_stone_slab",     2.0f,  6.0f,   true,  false, false, 0,  15, false, false},
    {BlockID::STONE_SLAB,          "stone_slab",            2.0f,  6.0f,   true,  true,  false, 0,  0,  false, false},
    {BlockID::BRICK_BLOCK,         "brick_block",           2.0f,  6.0f,   true,  false, false, 0,  15, false, false},
    {BlockID::TNT,                 "tnt",                   0,     0,      true,  false, true,  0,  15, false, false},
    {BlockID::BOOKSHELF,           "bookshelf",             1.5f,  1.5f,   true,  false, true,  0,  15, false, false},
    {BlockID::MOSSY_COBBLESTONE,   "mossy_cobblestone",     2.0f,  6.0f,   true,  false, false, 0,  15, false, false},
    {BlockID::OBSIDIAN,            "obsidian",             50,    1200,    true,  false, false, 0,  15, false, false},
    {BlockID::TORCH,               "torch",                 0,     0,      false, true,  false, 14, 0,  false, false},
    {BlockID::FIRE,                "fire",                  0,     0,      false, true,  false, 15, 0,  true,  false},
    {BlockID::MOB_SPAWNER,         "mob_spawner",           5.0f,  5.0f,   true,  true,  false, 0,  0,  false, false},
    {BlockID::OAK_STAIRS,          "oak_stairs",            2.0f,  3.0f,   true,  true,  true,  0,  0,  false, false},
    {BlockID::CHEST,               "chest",                 2.5f,  2.5f,   true,  true,  true,  0,  0,  false, false},
    {BlockID::REDSTONE_WIRE,       "redstone_wire",         0,     0,      false, true,  false, 0,  0,  false, false},
    {BlockID::DIAMOND_ORE,         "diamond_ore",           3.0f,  3.0f,   true,  false, false, 0,  15, false, false},
    {BlockID::DIAMOND_BLOCK,       "diamond_block",         5.0f,  6.0f,   true,  false, false, 0,  15, false, false},
    {BlockID::CRAFTING_TABLE,      "crafting_table",        2.5f,  2.5f,   true,  false, true,  0,  15, false, false},
    {BlockID::WHEAT,               "wheat",                 0,     0,      false, true,  false, 0,  0,  false, false},
    {BlockID::FARMLAND,            "farmland",              0.6f,  0.6f,   true,  true,  false, 0,  0,  false, false},
    {BlockID::FURNACE,             "furnace",               3.5f,  3.5f,   true,  false, false, 0,  15, false, false},
    {BlockID::FURNACE_LIT,         "furnace_lit",           3.5f,  3.5f,   true,  false, false, 13, 15, false, false},
    {BlockID::SIGN,                "sign",                  1.0f,  1.0f,   false, true,  true,  0,  0,  false, false},
    {BlockID::WOODEN_DOOR,         "wooden_door",           3.0f,  3.0f,   true,  true,  true,  0,  0,  false, false},
    {BlockID::LADDER,              "ladder",                0.4f,  0.4f,   false, true,  true,  0,  0,  false, false},
    {BlockID::RAIL,                "rail",                  0.7f,  0.7f,   false, true,  false, 0,  0,  false, false},
    {BlockID::COBBLESTONE_STAIRS,  "cobblestone_stairs",    2.0f,  6.0f,   true,  true,  false, 0,  0,  false, false},
    {BlockID::WALL_SIGN,           "wall_sign",             1.0f,  1.0f,   false, true,  true,  0,  0,  false, false},
    {BlockID::LEVER,               "lever",                 0.5f,  0.5f,   false, true,  false, 0,  0,  false, false},
    {BlockID::STONE_PRESSURE_PLATE,"stone_pressure_plate",  0.5f,  0.5f,   false, true,  false, 0,  0,  false, false},
    {BlockID::IRON_DOOR,           "iron_door",             5.0f,  5.0f,   true,  true,  false, 0,  0,  false, false},
    {BlockID::WOODEN_PRESSURE_PLATE,"wooden_pressure_plate",0.5f,  0.5f,   false, true,  true,  0,  0,  false, false},
    {BlockID::REDSTONE_ORE,        "redstone_ore",          3.0f,  3.0f,   true,  false, false, 0,  15, false, false},
    {BlockID::REDSTONE_ORE_LIT,    "redstone_ore_lit",      3.0f,  3.0f,   true,  false, false, 9,  15, false, false},
    {BlockID::REDSTONE_TORCH_OFF,  "redstone_torch_off",    0,     0,      false, true,  false, 0,  0,  false, false},
    {BlockID::REDSTONE_TORCH,      "redstone_torch",        0,     0,      false, true,  false, 7,  0,  false, false},
    {BlockID::BUTTON,              "button",                0.5f,  0.5f,   false, true,  false, 0,  0,  false, false},
    {BlockID::SNOW_LAYER,          "snow_layer",            0.1f,  0.1f,   false, true,  false, 0,  0,  true,  false},
    {BlockID::ICE,                 "ice",                   0.5f,  0.5f,   true,  true,  false, 0,  3,  false, false},
    {BlockID::SNOW,                "snow",                  0.2f,  0.2f,   true,  false, false, 0,  15, false, false},
    {BlockID::CACTUS,              "cactus",                0.4f,  0.4f,   true,  true,  false, 0,  0,  false, false},
    {BlockID::CLAY,                "clay",                  0.6f,  0.6f,   true,  false, false, 0,  15, false, false},
    {BlockID::REEDS,               "reeds",                 0,     0,      false, true,  false, 0,  0,  false, false},
    {BlockID::JUKEBOX,             "jukebox",               2.0f,  6.0f,   true,  false, true,  0,  15, false, false},
    {BlockID::FENCE,               "fence",                 2.0f,  3.0f,   true,  true,  true,  0,  0,  false, false},
    {BlockID::PUMPKIN,             "pumpkin",               1.0f,  1.0f,   true,  false, false, 0,  15, false, false},
    {BlockID::NETHERRACK,          "netherrack",            0.4f,  0.4f,   true,  false, false, 0,  15, false, false},
    {BlockID::SOUL_SAND,           "soul_sand",             0.5f,  0.5f,   true,  false, false, 0,  15, false, false},
    {BlockID::GLOWSTONE,           "glowstone",             0.3f,  0.3f,   true,  true,  false, 15, 0,  false, false},
    {BlockID::PORTAL,              "portal",               -1,     0,      false, true,  false, 11, 0,  false, false},
    {BlockID::JACK_O_LANTERN,      "jack_o_lantern",        1.0f,  1.0f,   true,  false, false, 15, 15, false, false},
    {BlockID::CAKE,                "cake",                  0.5f,  0.5f,   true,  true,  false, 0,  0,  false, false},
    {BlockID::REPEATER_OFF,        "repeater_off",          0,     0,      false, true,  false, 0,  0,  false, false},
    {BlockID::REPEATER_ON,         "repeater_on",           0,     0,      false, true,  false, 9,  0,  false, false},
    {BlockID::STAINED_GLASS,       "stained_glass",         0.3f,  0.3f,   true,  true,  false, 0,  0,  false, false},
    {BlockID::TRAPDOOR,            "trapdoor",              3.0f,  3.0f,   true,  true,  true,  0,  0,  false, false},
    {BlockID::MONSTER_EGG,         "monster_egg",           0.75f, 0.75f,  true,  false, false, 0,  15, false, false},
    {BlockID::STONEBRICK,          "stonebrick",            1.5f,  6.0f,   true,  false, false, 0,  15, false, false},
    {BlockID::BROWN_MUSHROOM_BLOCK,"brown_mushroom_block",  0.2f,  0.2f,   true,  false, true,  0,  15, false, false},
    {BlockID::RED_MUSHROOM_BLOCK,  "red_mushroom_block",    0.2f,  0.2f,   true,  false, true,  0,  15, false, false},
    {BlockID::IRON_BARS,           "iron_bars",             5.0f,  6.0f,   true,  true,  false, 0,  0,  false, false},
    {BlockID::GLASS_PANE,          "glass_pane",            0.3f,  0.3f,   true,  true,  false, 0,  0,  false, false},
    {BlockID::MELON_BLOCK,         "melon_block",           1.0f,  1.0f,   true,  false, false, 0,  15, false, false},
    {BlockID::PUMPKIN_STEM,        "pumpkin_stem",          0,     0,      false, true,  false, 0,  0,  false, false},
    {BlockID::MELON_STEM,          "melon_stem",            0,     0,      false, true,  false, 0,  0,  false, false},
    {BlockID::VINE,                "vine",                  0.2f,  0.2f,   false, true,  true,  0,  0,  true,  false},
    {BlockID::FENCE_GATE,          "fence_gate",            2.0f,  3.0f,   true,  true,  true,  0,  0,  false, false},
    {BlockID::BRICK_STAIRS,        "brick_stairs",          2.0f,  6.0f,   true,  true,  false, 0,  0,  false, false},
    {BlockID::STONE_BRICK_STAIRS,  "stone_brick_stairs",    1.5f,  6.0f,   true,  true,  false, 0,  0,  false, false},
    {BlockID::MYCELIUM,            "mycelium",              0.6f,  0.6f,   true,  false, false, 0,  15, false, false},
    {BlockID::WATERLILY,           "waterlily",             0,     0,      false, true,  false, 0,  0,  false, false},
    {BlockID::NETHER_BRICK,        "nether_brick",          2.0f,  6.0f,   true,  false, false, 0,  15, false, false},
    {BlockID::NETHER_BRICK_FENCE,  "nether_brick_fence",    2.0f,  6.0f,   true,  true,  false, 0,  0,  false, false},
    {BlockID::NETHER_BRICK_STAIRS, "nether_brick_stairs",   2.0f,  6.0f,   true,  true,  false, 0,  0,  false, false},
    {BlockID::NETHER_WART,         "nether_wart",           0,     0,      false, true,  false, 0,  0,  false, false},
    {BlockID::ENCHANTING_TABLE,    "enchanting_table",      5.0f,  1200,   true,  true,  false, 7,  0,  false, false},
    {BlockID::BREWING_STAND,       "brewing_stand",         0.5f,  0.5f,   true,  true,  false, 1,  0,  false, false},
    {BlockID::CAULDRON,            "cauldron",              2.0f,  2.0f,   true,  true,  false, 0,  0,  false, false},
    {BlockID::END_PORTAL,          "end_portal",           -1,    18000000, false, true,  false, 15, 0,  false, false},
    {BlockID::END_PORTAL_FRAME,    "end_portal_frame",     -1,    18000000, true,  false, false, 1,  15, false, false},
    {BlockID::END_STONE,           "end_stone",             3.0f,  9.0f,   true,  false, false, 0,  15, false, false},
    {BlockID::DRAGON_EGG,          "dragon_egg",            3.0f,  9.0f,   true,  true,  false, 1,  0,  false, true},
    {BlockID::REDSTONE_LAMP,       "redstone_lamp",         0.3f,  0.3f,   true,  false, false, 0,  15, false, false},
    {BlockID::REDSTONE_LAMP_LIT,   "redstone_lamp_lit",     0.3f,  0.3f,   true,  false, false, 15, 15, false, false},
    {BlockID::EMERALD_ORE,         "emerald_ore",           3.0f,  3.0f,   true,  false, false, 0,  15, false, false},
    {BlockID::ENDER_CHEST,         "ender_chest",          22.5f, 600,     true,  true,  false, 7,  0,  false, false},
    {BlockID::EMERALD_BLOCK,       "emerald_block",         5.0f,  6.0f,   true,  false, false, 0,  15, false, false},
    {BlockID::COMMAND_BLOCK,       "command_block",        -1,    18000000, true,  false, false, 0,  15, false, false},
    {BlockID::BEACON,              "beacon",                3.0f,  3.0f,   true,  true,  false, 15, 0,  false, false},
    {BlockID::ANVIL,               "anvil",                 5.0f,  1200,    true,  true,  false, 0,  0,  false, true},
    {BlockID::TRAPPED_CHEST,       "trapped_chest",         2.5f,  2.5f,   true,  true,  true,  0,  0,  false, false},
    {BlockID::QUARTZ_ORE,          "quartz_ore",            3.0f,  3.0f,   true,  false, false, 0,  15, false, false},
    {BlockID::HOPPER,              "hopper",                3.0f,  3.0f,   true,  true,  false, 0,  0,  false, false},
    {BlockID::QUARTZ_BLOCK,        "quartz_block",          0.8f,  0.8f,   true,  false, false, 0,  15, false, false},
    {BlockID::SLIME_BLOCK,         "slime_block",           0,     0,      true,  true,  false, 0,  0,  false, false},
    {BlockID::BARRIER,             "barrier",              -1,    18000004, true,  true,  false, 0,  0,  false, false},
    {BlockID::SEA_LANTERN,         "sea_lantern",           0.3f,  0.3f,   true,  true,  false, 15, 0,  false, false},
    {BlockID::PACKED_ICE,          "packed_ice",            0.5f,  0.5f,   true,  false, false, 0,  15, false, false},
};
// clang-format on

constexpr size_t BLOCK_PROPERTIES_COUNT = sizeof(BLOCK_PROPERTIES) / sizeof(BLOCK_PROPERTIES[0]);

// Lookup functions - linear scan over the sparse table.
// For hot-path usage, build a 256-entry lookup array at init time.
inline const BlockProperties& get_block_properties(BlockID id) {
    for (size_t i = 0; i < BLOCK_PROPERTIES_COUNT; ++i) {
        if (BLOCK_PROPERTIES[i].id == id) {
            return BLOCK_PROPERTIES[i];
        }
    }
    return BLOCK_PROPERTIES[0]; // AIR fallback
}

inline bool is_solid(BlockID id) {
    return get_block_properties(id).solid;
}

inline bool is_liquid(BlockID id) {
    auto raw = static_cast<uint16_t>(id);
    return raw >= 8 && raw <= 11; // WATER, WATER_STILL, LAVA, LAVA_STILL
}

inline bool can_place_over(BlockID id) {
    return get_block_properties(id).replaceable;
}

inline uint8_t get_light_level(BlockID id) {
    return get_block_properties(id).light_emission;
}

} // namespace mc189
